# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-09 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('courseId', models.CharField(max_length=200)),
                ('courseName', models.CharField(max_length=200)),
                ('departmentName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('departmentId', models.CharField(max_length=200)),
                ('departmentName', models.CharField(max_length=200)),
            ],
        ),
    ]
